### ISSUE TITLE
Configure Project for "Prebuilt Bokeh Extensions"

### ISSUE THREAD

**Issue by MarcSkovMadsen** [MarcSkovMadsen/panel-chemistry#3]
We also need to setup the project to support pre-built *Bokeh Extensions*. 

This is described in https://awesome-panel.readthedocs.io/en/latest/guides/awesome-panel-extensions-guide/bokeh-extensions.html#prebuilt-bokeh-extensions. If possible we should record and distribute this as a video to make it easier for the Panel Community to build new packages/ extensions in the future.

**Comment by ea42gh** [comment]
I'll volunteer to do the video part (at least the editing :-)

**Comment by MarcSkovMadsen** [comment]
Done
